title: "我的网站"
description: "个人网站 & 博客"
author: "swx"
url: "https://songwangxi.github.io"
baseurl: ""

include:
  - _includes

exclude:
  - share/
  - tools/
  - README.md
  - .gitignore
  - wrangler.jsonc
