title: "我的博客"
description: "记录学习与生活"
author: "swx"
url: "https://songwangxi.github.io"
baseurl: "/blog"           # 核心：告诉 Jekyll 博客在子目录

permalink: /blog/:year/:month/:day/:title/

# 禁用默认主题
theme: null

# 让博客能找到根目录的 _includes
includes_dir: ../_includes
