title: "我的博客"
description: "记录学习与生活"
author: "swx"
url: "https://songwangxi.github.io"
baseurl: "/blog"

permalink: /blog/:year/:month/:day/:title/

# 禁用默认主题
theme: null

# 关键：让 blog 子目录使用根目录的 _includes
includes_dir: ../_includes
